# fly.toml app configuration file generated for pagina-proof on 2024-07-18T17:42:24-06:00
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = 'pagina-proof'
primary_region = 'qro'

[build]

[http_service]
  internal_port = 8080
  force_https = true
  auto_stop_machines = true
  auto_start_machines = true
  min_machines_running = 0
  processes = ['app']

[[vm]]
  memory = '1gb'
  cpu_kind = 'shared'
  cpus = 1
